train_data_path: /home/kostya_fs/code/linkman_2d_dataset/train/
val_data_path: /home/kostya_fs/code/linkman_2d_dataset/validation/
test_data_path: /home/kostya_fs/code/linkman_2d_dataset/test/
exclude_train_data: ''
exclude_val_data: ''
exclude_test_data: ''

project_name: LinkMan2D
entity: kostya_fs

model_type: semilinear

batch_size: 1000

main_metric: traj_ate
layers_num: 3                  # [0:5]  ## HIDDEN
hidden_size: 64                # [32,64,128]
activation_function: relu      # (relu or elu) 

num_epochs: 25
rollout_size: 150             # used in predict_multi_step
learning_rate: 0.01           # [0.001:0.0001]

plot_trajectories: True
save_to_csv: True


